# Как далеко игрок сможет отойти от того, кто захватил его поводком.
# Право - playerleash.move
# в блоках
max move distance: 7

# Частота синхронизации местоположений. В этот тик может немного поменяться взгляд игрока
# поэтому лучше ставить более 10. Но слишком большие значения могут привести к телепортации
# в тиках
sync period: 15

# Если on, то работает только на 1.16.4
# Если off, то будет спавнить с задержкой и возможно будет конфликт плагинов
nms: on